version: "3.2"
services:
  node:
    build:
      context: ../
      dockerfile: ./docker/node/Dockerfile
    working_dir: /var/app
    env_file:
      - ./../.env
    ports:
      - 3000:3000
    volumes:
      - ../:/var/app
      - node_modules:/var/app/node_modules
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://db:3306
    command: yarn dev
    links:
      - db
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 3306:3306
volumes:
  node_modules:
    driver: local
  mysql_data:
    driver: local
